### ISSUE TITLE
What is rate limit ? 

### ISSUE THREAD

**Issue by ttpro1995** [estiens/world_cup_json#101]
Is there any rate limit for API.
I am intend to update realtime for my application. So I would hit 1~2 request per minutes. Is it possible ?

**Comment by estiens** [comment]
That's totally fine. You will start getting throttled somewhere around more than 2 requests every 5 seconds. Try to keep it as close to once every 30s-1 minute as you because the data isn't getting updated any quicker than that...

**Comment by estiens** [comment]
Note, increasing throttling a bit to 3 requests in 30 seconds to help manage server load. Please set your realtime bots to poll no quicker than once every 30 seconds.
