### ISSUE TITLE
Filter matches by date

### ISSUE THREAD

**Issue by thonglh** [estiens/world_cup_json#102]
Currently, we have API to fetch matches in `today/tomorrow` but we may need data from `yesterday` or on a specific day eg. `Jun 18`...

It will be helpful if we have a controller method for that, I have seen the model filter function for it.

**Comment by estiens** [comment]
yes, I just forgot to add the endpoint filter, I'll add it in today!

**Comment by estiens** [comment]
This is in the readme and deployed now, thx for reminder!
