### ISSUE TITLE
Request to add new features

### ISSUE THREAD

**Issue by Angelk90** [estiens/world_cup_json#104]
@estiens : 
Hi, congratulations for the excellent work.

It would be possible to add the following characteristics, if they are always possible to find them, in all the api. ;)

1) Data stadium number of people attending the match.

2) Weather:
Conditions,
temperatures,
Humidity,
Wind.

3) Name and info of the Referee:
Main Referee,
Lineman 1,
Lineman 2,
Fourth Official,
Video Assistant Referee (VAR),
offside VAR,
Assist VAR,
Support VAR,
Referee's Reserve Assist.

4) Statistical data:
punishments,
goalie's parades,
referral kicks,
lineouts,
second yellow card and red card,
free kicks,
saves.

5) The best man game:
who is,
shots,
goals made by him,
distance covered,
other info.

5) Team formations:
players in the field,
players on the bench,
coaches (ct),
their shirt number and in what role they play.

6) When there is a substitution it would be possible to specify who is replaced with whom and what number of meshes they have.

7) The type of training in the field: 4-2-3-1, 4-5-1, ...

8) Api for the player info:
date of birth,
height,
weight,
other info,
shirt number,
position,
goals (saves if it is bring),
assists,
on-target,
off-target,
shots (defender),
blocked (defender),
played matches,
minuted played,
committed fouls,
yellow cards,
red cards,
starting play (against who).

I apologize for the length of the matter and the number of requests, but it would be very important.

**Comment by estiens** [comment]
People are welcome to add all these things if they want and create endpoints for more detailed info :) I don't think I'll be adding much new stuff now that we have in game events (subs, cards, etc) and match statistics (possession %, shots on target, shots off target, etc)

**Comment by Angelk90** [comment]
@estiens : So which of these points could be made? For example, I am working on this given the array of two teams, I do this:![](https://i.imgur.com/LCth9gI.jpg)

**Comment by estiens** [comment]
Looks awesome, and I think that information is somewhere on the FIFA site if you want to try to grab it with a scraper and either extend this scraper or write your own, but unfortunately just keeping this running fast and bug free at this point, don't think I'll be able to add any new features myself.

**Comment by pravinjoshua** [comment]
Hi , Would you add an end point for top scorers list ? 

Highly appreciate what you have done.
