### ISSUE TITLE
Duplicate goal event in Poland v Senegal

### ISSUE THREAD

**Issue by jthomas** [estiens/world_cup_json#105]
Found this today whilst using the API...

```
{"id":224,"type_of_event":"goal-own","player":"Thiago CIONEK","time":"37'"}
{"id":223,"type_of_event":"goal-own","player":"Thiago CIONEK","time":"38'"}
```

Assume it's an issue with the FIFA site but just thought I'd let you know.

**Comment by estiens** [comment]
Yes, it gets scraped and created, then the Fifa site deletes that event and creates a new one with a new minute and another one gets created. There used to be a unique event_id that I could grab in 2014, but this time we have to match on player/type/time to not create a duplicate.

Not sure how to make sure I don't exclude events. Guess I would probably be safe doing something like if an event is the same event and the same player and occurs within one minute of each other, delete the older one, but someone could score twice in one or two minutes so....

**Comment by jthomas** [comment]
Yeah, that's a pain! I'll close this issue and it's not something you can manage. Thanks again for the API!

**Comment by estiens** [comment]
I'm open to any ideas! I could also delete any event that doesn't exist on the page anymore, but that leaves us vulnerable to a bug where events disappear temporarily and increases processing time on each scrape.

Possibly after a match is marked complete, I'll make one last run-through and re-create all the events. This will help us with missing very late match events that only show up on the page after the match is marked full-time and keep the historical data as accurate as possible, while deferring to not missing any event for those using it real time.

**Comment by jthomas** [comment]
Might be worth waiting to see if this happens again. If it's (relatively) irregular 🤷‍.

**Comment by estiens** [comment]
I know, it's happened at least twice so far that I heard of...guessing that an event is entered immediately and then the official time is checked so sometimes it gets entered for 50' and then is changed to 51'

**Comment by mdenton8** [comment]
It happens pretty frequently with the yellow card times, there are a lot of duplicate yellow card events.

Thanks for the awesome API though!

**Comment by mdenton8** [comment]
See Morocco-Spain, the yellow card events 619 and 620 are duplicated, and so are 653 and 654. I like the idea of recreating all the events after the game is marked final.

**Comment by estiens** [comment]
yeah, I'm just worried about all the slackbots that tweet out every time a new event is created. The easiest would be to destroy and re-create all events after a match is complete, but that seems like it could lead to annoyed emails about new events.
