### ISSUE TITLE
Optimal API call interval for real time update

### ISSUE THREAD

**Issue by ttpro1995** [estiens/world_cup_json#111]
I would like to notify user when there are event like goals, ... 
What is optimal API call interval should I make ?
Currently I call once every 15 seconds (on centralize server, not client device).

**Comment by estiens** [comment]
That should be fine, you can even slow it down a little. I'm scraping somewhere between every 30-60 seconds, and there is a bit of a cache, so you probably won't get new information until at least 40 seconds later. I usually use 1 minute pings, I've seen other ppl use every 30 seconds. The current throttle is 10 requests every 60 seconds.
