### ISSUE TITLE
Heroku setup

### ISSUE THREAD

**Issue by simofacc** [estiens/world_cup_json#113]
Hi,

I am trying to setup the repo on a heroku instance but when I run `heroku run rake fifa:get_all_matches` I get an error `Selenium::WebDriver::Error::WebDriverError: unable to connect to chromedriver 127.0.0.1:9515`.

Any idea what's wrong? I installed the chrome and chromedriver using the heroku buildpacks.

**Comment by estiens** [comment]
Have you pulled down the latest master? We have to set the chromedriver path...

I've actually rewritten the scrapers and just deployed them this morning. You can look in scrapers/scraper_tasks, but you should be able to set everything up by running

scrape_old_matches 
scrape_future_matches
scrape_for_events
scrape_for_stats

and then once those all complete (you'll prob get some memory errors on heroku) you can just put

ScraperTasks.scrape_for_goals on a repeating clock

Of course the older rake tasks are still there and still work

You can get that error intermittently if you run out of ram as well, need to run those rake tasks in at least a 2x dyno

**Comment by estiens** [comment]
seems to be a memory leak in the new scraper though...so maybe use the old one for now :)

**Comment by simofacc** [comment]
I managed to get it to work as there were some bugs in the match scraper task. The @browser var was missing the @.

`
def get_page_from_url(url)
  @browser = init_browser
  @browser.goto(url)
  Nokogiri::HTML(@browser.html)
end
`

Also on heroku it creates 3 dynos web, clock and worker. Do all 3 dynos need to be online for the api to work or just the first 2? And is there any cheaper alternative to heroku to get this running?

**Comment by simofacc** [comment]
I also noticed that I am getting some weird datetime values, in the sense that the start time of the game is wrong. Any idea what could be the issue?

**Comment by estiens** [comment]
@simofacc -- if there was a bug you haven't pulled down latest master :) 

The worker dyno isn't used, but it will be when the scraper tasks are running in sidekiq.

You might be getting some weird TZ conversion issues.

**Comment by simofacc** [comment]
@estiens heroku should be on UTC by default but somehow it's not saving times in UTC timezone. Now I configured the timezone manually but since the timezone is not correctly saved in the database I cannot localise the time properly.

**Comment by estiens** [comment]
Might have to play with converting on the way in -- but I don't think any of the old or new scraper code is doing any conversions anywhere anymore - it grabs a UTC string from the site and then saves it directly to the database. Try setting config.timezone = UTC on heroku just to make sure?

**Comment by simofacc** [comment]
@estiens I found the issue. The time on the fifa website is in local time depending on the location of where the game is going to be played. At some point in the code the time was parsed using the local time zone `datetime = ActiveSupport::TimeZone[timezones[location]].parse(datetime).localtime` but this is not done anymore.

**Comment by estiens** [comment]
ok great! If you notice any issues with the scraped data going forward for knockout matches, maybe resubmit that in a PR? It's changed a few times!

**Comment by estiens** [comment]
@simofacc there is a new scraper task called fix times that should fix any time issues except for one past match (France V Australia) that needs to be fixed manually
