### ISSUE TITLE
Dublicate event 223 and 224 in match id 300331545 

### ISSUE THREAD

**Issue by ttpro1995** [estiens/world_cup_json#114]
In https://worldcup.sfg.io/matches/300331545 
Event 223 and 224 is dublicated

```

{"id":224,"type_of_event":"goal-own","player":"Thiago CIONEK","time":"37'"}
{"id":223,"type_of_event":"goal-own","player":"Thiago CIONEK","time":"38'"}
```

**Comment by jthomas** [comment]
More discussion on this here: https://github.com/estiens/world_cup_json/issues/105#event-1694510672

**Comment by estiens** [comment]
yes known issue

at some point I might try to write logic that says if an event exists within one minute and the old event no longer exists in the scraped page, change the old event time to the new event time, but at the moment I'd rather have occasional extra information than worry about somehow missing information.
