### ISSUE TITLE
Wrong datetimes in today's matches (22/06/18)

### ISSUE THREAD

**Issue by spapas** [estiens/world_cup_json#115]
Here's the json:

```
[{
	"venue": "St. Petersburg",
	"location": "Saint Petersburg Stadium",
	"status": "future",
	"time": null,
	"fifa_id": "300331540",
	"home_team_statistics": null,
	"away_team_statistics": null,
	"datetime": "2018-06-22T15:00:00Z",
	"last_event_update_at": null,
	"last_score_update_at": "2018-06-21T11:54:50Z",
	"home_team": {
		"country": "Brazil",
		"code": "BRA",
		"goals": 0
	},
	"away_team": {
		"country": "Costa Rica",
		"code": "CRC",
		"goals": 0
	},
	"winner": null,
	"winner_code": null,
	"home_team_events": [],
	"away_team_events": []
}, {
	"venue": "Volgograd",
	"location": "Volgograd Arena",
	"status": "future",
	"time": null,
	"fifa_id": "300331497",
	"home_team_statistics": null,
	"away_team_statistics": null,
	"datetime": "2018-06-22T18:00:00Z",
	"last_event_update_at": null,
	"last_score_update_at": "2018-06-21T11:54:50Z",
	"home_team": {
		"country": "Nigeria",
		"code": "NGA",
		"goals": 0
	},
	"away_team": {
		"country": "Iceland",
		"code": "ISL",
		"goals": 0
	},
	"winner": null,
	"winner_code": null,
	"home_team_events": [],
	"away_team_events": []
}, {
	"venue": "Kaliningrad",
	"location": "Kaliningrad Stadium",
	"status": "future",
	"time": null,
	"fifa_id": "300340183",
	"home_team_statistics": null,
	"away_team_statistics": null,
	"datetime": "2018-06-22T20:00:00Z",
	"last_event_update_at": null,
	"last_score_update_at": "2018-06-21T11:54:50Z",
	"home_team": {
		"country": "Serbia",
		"code": "SRB",
		"goals": 0
	},
	"away_team": {
		"country": "Switzerland",
		"code": "SUI",
		"goals": 0
	},
	"winner": null,
	"winner_code": null,
	"home_team_events": [],
	"away_team_events": []
}]
```

**Comment by gurka** [comment]
Well the date is correct (today is 2018-06-22, or 22/06/18), but the times are wrong. Brazil - Costa Rica starts at 12:00 UTC , so it should say 12:00:00Z and not 15:00:00Z. The same applies for all (?) matches after today. All times seems to be +3 hours wrong.

**Comment by spapas** [comment]
Yes of course, the times  are wrong. It's a datetime field in the JSON that's why I wrote dates in the issue title.

**Comment by gurka** [comment]
Your title suggest that there are something wrong with the dates as well, since you wrote 23/06 but pasted json for 22/06

**Comment by spapas** [comment]
Title changed :)

**Comment by gilbitron** [comment]
I can confirm the dates are wrong today. They are either missing a timezone or have not been converted to UTC.

**Comment by andyewen** [comment]
https://github.com/estiens/world_cup_json/blob/8c182c2ebf6c72fe7fb243de131846d6391d5c93/lib/scrapers/scraper_match.rb#L13 looks like it's scraping the content of the "13:00 Local Time" section on the /matches FIFA site.
Looks like that element has the UTC time as an attribute which could be scraped instead?
```
<div class="fi-mu__info__datetime" data-utcdate="2018-06-22T12:00:00.000Z">
    22 Jun 2018 - 15:00
    <span class="fi-mu__info__localtime">Local time</span>
</div>
```

**Comment by estiens** [comment]
yeah, it should be scraping the UTC time, it must have overwritten the times when I deployed the new scrapers (that last one wasn't changing the time), I'll get it fixed here shortly, thanks for reporting.

**Comment by estiens** [comment]
hrmmm...FIFA bug to work around it looks like, or something going on, about every fourth match now has the right time but the wrong date. If you ever would have told me that my hardest taks in programming was dealing with dates....fix forthcoming soom

Or if someone wants to just upload a JSON file with fifa match id and UTC date time and I can parse from that once and for all and deal with a reschedule if it happens manually...

**Comment by estiens** [comment]
Ah, there is a bug on the FIFA site for the UTC date value -- for afternoon matches in UTC (say at 3 PM) they use 03:00 in the timestring instead of 15:00 -- have to go back to parsing by localtime arghhhh

**Comment by estiens** [comment]
Ok, hacky workaround in place right now...feel free to let me know if you still see any issues.
Even if someone doesn't know Ruby all I need to fix once in for all is a file (whatever JSON, YML, etc) that has

```yml
matches:
  -fifa_id: foo
  datetime: 2018-06-021T13:00:00Z
  -fifa_id: bar
  datetime: 2018-06-021T18:00:00Z
```

**Comment by padraic-padraic** [comment]
Thank you for working on this! We all really appreciate it, must be a headache to parse someone else's website...

**Comment by estiens** [comment]
scraping is.a PITA yes :D

**Comment by JonnoN** [comment]
definitely thank you!
Mostly fixed... just one more thing I can see... the current game, SRB v SUI, has the datetime wrong.

"2018-06-22T06:00:00Z"

**Comment by estiens** [comment]
ah, i didn't have anything update on a live match out of fear that if it went wrong and everyone's slack bots started pinging I'd have 100 tweets at me. I'll update it manually :)

**Comment by estiens** [comment]
ok, fixed that now :)

**Comment by spapas** [comment]
Yes it works thank you very much!

PS here's my toy app that's using your API https://spapas.github.io/wc2018/

**Comment by DeBuchie** [comment]
For the FRA v AUS game the API seems to give the value of `2018-06-16T22:00:00Z` but it's supposed to be `2018-06-16T10:00:00.000Z`. (Basically 10 AM instead of 10 PM). 

Thx for your work.

**Comment by estiens** [comment]
ah, because that was the only one that was before 12 UTC that actually WAS before 12 UTC. Spot checked the rest, all seems good, thanks for the catch!
