### ISSUE TITLE
Add team-lineup for every match.

### ISSUE THREAD

**Issue by nSpider** [estiens/world_cup_json#116]
Hello guys, it's not an issue actually but, is it possible to add team-lineup for every match? If so, it will be great.

**Comment by nSpider** [comment]
That's great. Waiting for the update...!!!

**Comment by nSpider** [comment]
Just a suggestion, can you scrape from third party websites other than FIFA? like goal.com, etc.

**Comment by estiens** [comment]
yeah you would have to either switch entirely and us a different unique ID or match on FIFA site by datetime and teams

**Comment by estiens** [comment]
Starting 11 and subs are part of all past matches now and should come in when a match starts. Players show up with position, captain status, jersey number, and name

**Comment by simofacc** [comment]
@estiens Which task should get the starting_eleven? I ran most of them and also tried fifa:get_events but it didn't pull the lineups for the old matches.

**Comment by estiens** [comment]
The new JSON task will...it will run with the clock but first you have to run

Scrapers::ScraperTasks.setup_matches_for_json

You can pull in historic data with write_old_match_json

**Comment by simofacc** [comment]
@estiens When I run Scrapers::ScraperTasks.write_old_match_json I get an empty array

**Comment by estiens** [comment]
Did you run Scrapers::ScraperTasks.setup_matches_for_json first? that sets all the unique IDs that we need to generate the match URLs for pulling in specifics

**Comment by simofacc** [comment]
@estiens yes I did do that

**Comment by simofacc** [comment]
What is the unique Id name I should look for? I got something like the below as an output

`=> [#<Match id: 5, fifa_id: "300331533", location: "Kazan Arena", datetime: "2018-06-16 22:00:00", home_team_id: 9, away_team_id: 10, home_team_tbd: nil, away_team_tbd: nil, teams_scheduled: nil, home_team_score: 2, away_team_score: 1, status: "end of time", created_at: "2018-06-22 22:41:09", updated_at: "2018-06-26 13:13:06", home_team_penalties: nil, away_team_penalties: nil, venue: "Kazan", time: "full-time", last_score_update_at: "2018-06-22 23:09:53", last_event_update_at: "2018-06-22 23:09:53", stats_complete: true, winner_id: 9, draw: false, events_complete: true, fifa_competition_id: "17", fifa_season_id: "254645", fifa_group_id: "275079", fifa_stage_id: "275073", stage_name: "First stage", weather: nil, attendance: nil, json_home_team_score: nil, json_away_team_score: nil, json_home_team_penalties: nil, json_away_team_penalties: nil, officials: nil>, #<Match id: 8, fifa_id: "300331523", location: "Kaliningrad Stadium", datetime: "2018-06-16 19:00:00", home_team_id: 15, away_team_id: 16, home_team_tbd: nil, away_team_tbd: nil, teams_scheduled: nil, home_team_score: 2, away_team_score: 0, status: "end of time", created_at: "2018-06-22 22:41:09", updated_at: "2018-06-26 13:13:06", home_team_penalties: nil, away_team_penalties: nil, venue: "Kaliningrad", time: "full-time", last_score_update_at: "2018-06-22 23:10:23", last_event_update_at: "2018-06-22 23:10:24", stats_complete: true, winner_id: 15, draw: false, events_complete: true, fifa_competition_id: "17", fifa_season_id: "254645", fifa_group_id: "275081", fifa_stage_id: "275073", stage_name: "First stage", weather: nil, attendance: nil, json_home_team_score: nil, json_away_team_score: nil, json_home_team_penalties: nil, json_away_team_penalties: nil, officials: nil>, #<Match id: 13, fifa_id: "300331539", location: "Fisht Stadium", datetime: "2018-06-18 15:00:00", home_team_id: 25, away_team_id: 26, home_team_tbd: nil, away_team_tbd: nil, teams_scheduled: nil, home_team_score: 3, away_team_score: 0, status: "end of time", created_at: "2018-06-22 22:41:10", updated_at: "2018-06-26 13:13:06", home_team_penalties: nil, away_team_penalties: nil, venue: "Sochi", time: "full-time", last_score_update_at: "2018-06-22 23:12:03", last_event_update_at: "2018-06-22 23:12:05", stats_complete: true, winner_id: 25, draw: false, events_complete: true, fifa_competition_id: "17", fifa_season_id: "254645", fifa_group_id: "275087", fifa_stage_id: "275073", stage_name: "First stage", weather: nil, attendance: nil, json_home_team_score: nil, json_away_team_score: nil, json_home_team_penalties: nil`

**Comment by simofacc** [comment]
@estiens Ok I think I found the issue. Somehow my matches status in the database are saved as **end of time** but the query is looking for a status of **completed** so it's not finding any matches.

**Comment by estiens** [comment]
ah yes, sorry about that, so many changes every day it's hard for me to keep track of set up for a new database -- you can run scrape_for_events and scrape_for_stats and it will grab those and then mark it completed once it is sure the game is over and it has all the events.
