### ISSUE TITLE
step by step setup 

### ISSUE THREAD

**Issue by ttpro1995** [estiens/world_cup_json#119]
I want to run on my server (or heroku) but I have no idea about ruby. 

Tried: 
clone the git
install ruby, rake package 
Run rake db:setup setup:generate_teams 

```
➜  world_cup_json git:(master) rake db:setup setup:generate_teams --trace
rake aborted!
LoadError: cannot load such file -- bundler/setup
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/thaithien/workplace/github/world_cup_json/config/boot.rb:4:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/thaithien/workplace/github/world_cup_json/config/application.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/thaithien/workplace/github/world_cup_json/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:104:in `block in load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:103:in `load_rakefile'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:82:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

Did I miss something ?

**Comment by ttpro1995** [comment]
I try to deploy on heroku but get error

```
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Airbrake::Error: :project_key is required
```
What should I do ?

**Comment by simofacc** [comment]
@ttpro1995 the API uses Airbrake as an error logger. You can simply remove airbrake.rb from the config/initializers folder and probably you could also remove the gem `gem uninstall airbrake`.

Then you can add a cheaper alternative like Sentry for example so you can get alerts when there are any errors.

**Comment by ttpro1995** [comment]
airbrake is not the only problem. I manage to remove airbrake, but it still not work out-of-the-box 

Do I need to do something before or after 
`git push heroku master `

**Comment by simofacc** [comment]
@ttpro1995 I usually run ‘bundle install’ to update the Gemfile.lock before pushing to heroku.

**Comment by estiens** [comment]
`gem install bundler`
`bundle install`
`bundle exec rake db:drop db:create db:migrate setup:generate_teams`

Should get you running locally to run the tasks to scrape old and future matches. 

Note, you cannot run this on heroku on free dynos, they'll crash and run out of memory while scraping if that's a concern, I'd try to get it running locally first.

**Comment by simofacc** [comment]
I setup Dokku on Digital Ocean instead of Heroku. Price-wise it's far better and you get a greater selection if you want more processing power.

**Comment by ttpro1995** [comment]
@simofacc  how to set up on Dokku. I am trying but can get it show a web

**Comment by simofacc** [comment]
@ttpro1995 Did you manage to setup dokku correctly first? You will need to add a **.buildpacks** file in the root of the project so that Dokku can download the necessary buildpacks that are used on heroku.

Here are the buildpacks needed.
https://gist.github.com/simofacc/e8e3d77a95cd05bfba6fa4b8a378809a

Then you just add the dokku branch to the repo like heroku and do `git push dokku master` which should start the deploy. Most probably your issue must be with the missing buildpacks, but at the end of the push you should get a message `Application deployed: http://xxx https://`. Did you get that message?

**Comment by ttpro1995** [comment]
@simofacc I use Digital Ocean 1-click Dokku, so I don;t have problem with Dokku. 
I manage to get the web up (and bind to port 80). But look like it cannot crawl any data.  
Endpoint `/matches`  shows  `[]`

I put my thing here https://github.com/ttpro1995/world_cup_json  (branch tdev is what I push to Dokku)

**Comment by simofacc** [comment]
@ttpro1995 Ok yeah for the crawling you need to create 4 cron jobs on the server. Right now I have 4 tasks running https://gist.github.com/simofacc/1976ea6f53e285b627709046e9d1c336

In heroku the scraping tasks are run automatically as there are separate dynos created, but for dokku it seems that you have to do them manually. So keep an eye on the readme file so when there are new scraping tasks you can update the cron jobs.

**Comment by ttpro1995** [comment]
When run `dokku --rm-container run world-cup-json rake scraper:run_scraper

got error 
`
Selenium::WebDriver::Error::WebDriverError:  Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
`

I already put ChromeDriver to system path. Can start chromedriver from terminal 

```
root@dokku-s-1vcpu-3gb-sgp1-01:~# chromedriver
Starting ChromeDriver (v2.9.248304) on port 9515
```

**Comment by simofacc** [comment]
@ttpro1995 the issue with the chromedriver is that the path after the installation on the server might be different than the path specified in the code. Run `which chromedriver` on the server to get the path of the chromedriver. Then in the code find **Selenium::WebDriver::Chrome.driver_path** and change the path to the one you get on the server. Commit and push the code again.

On heroku there are some environment variables that are predefined for the chromedriver such as GOOGLE_CHROME_SHIM but I never got it to work there either, so I had to use the custom path I get from the server.

**Comment by ttpro1995** [comment]
I set 

`dokku config:set GOOGLE_CHROME_SHIM=/root/dep/chromedriver`

But somehow Dokku doesn't see that

**Comment by simofacc** [comment]
@ttpro1995 You forgot to specify the name of the app in your command

`dokku config:set myapp SOME_SECRET_VAR='hello'`

**Comment by ttpro1995** [comment]
Why chrome drive is not a file ? 

root@dokku-s-1vcpu-3gb-sgp1-01:~# dokku --rm-container run world-cup-json rake scraper:run_scraper
rake aborted!
Selenium::WebDriver::Error::WebDriverError: not a file: "/home/dokku/chrome/chromedriver"
/app/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/platform.rb:123:in `assert_file'
/app/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/common/platform.rb:127:in `assert_executable'
/app/vendor/bundle/ruby/2.5.0/gems/selenium-webdriver-3.12.0/lib/selenium/webdriver/chrome.rb:30:in `driver_path='
/app/lib/scrapers/base_scraper.rb:23:in `init_browser'
/app/lib/scrapers/base_scraper.rb:8:in `initialize'
/app/lib/scrapers/match_scraper.rb:7:in `initialize'
/app/lib/scrapers/scraper_tasks.rb:172:in `new'
/app/lib/scrapers/scraper_tasks.rb:172:in `scrape_matches'
/app/lib/scrapers/scraper_tasks.rb:103:in `check_for_live_game'
/app/lib/scrapers/scraper_tasks.rb:13:in `scrape_your_heart_out'
/app/lib/tasks/new_scraper.rake:4:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
Tasks: TOP => scraper:run_scraper
(See full trace by running task with --trace)
root@dokku-s-1vcpu-3gb-sgp1-01:~# /home/dokku/chrome/chromedriver
Starting ChromeDriver (v2.9.248304) on port 9515
