### ISSUE TITLE
Goals assigned to different game

### ISSUE THREAD

**Issue by qczy** [estiens/world_cup_json#122]
Currently played games (both at the same time - maybe this is a clue) and goal is assigned to Saudi Arabia (but no events occured). Different situation in other game: no goals assigned but one event type="goal" occured.

Real situation is: KSA:EGY is 0:0, and URU:RUS is 1:0. So the points are mismatched.

dump from "current" endpoint and/or from "today":

,"fifa_id":"300331509"
,"home_team":{"country":"Saudi Arabia","code":"KSA","goals":1}
,"away_team":{"country":"Egypt","code":"EGY","goals":0}
,"home_team_events":[]
,"away_team_events":[]

,"fifa_id":"300331516"
,"home_team":{"country":"Uruguay","code":"URU","goals":0}
,"away_team":{"country":"Russia","code":"RUS","goals":0}
,"home_team_events":[{"id":583,"type_of_event":"goal","player":"Luis SUAREZ","time":"10'"}]

Great code though.
Regards.

**Comment by qczy** [comment]
workaround: for results only swap fifa_id: 300331516 and 300331509

**Comment by pawelad** [comment]
Yeah, just noticed this as well - I'm guessing that this is the first time that 2 games are played at the same time and the crawler parses the wrong thing.

I'm not really good with Ruby but I'll try and debug this if I have a free moment.

**Comment by bklaas** [comment]
The workaround will help with this set of simultaneous matches, but there are more coming this week, even later today. Will need a real fix to put a stopper in this.

**Comment by estiens** [comment]
yeah, we're only scraping goals and events from the actual match details page for a specific match so I'm not sure what's going on but I'll check into it -- we'll get er fixed!

**Comment by adamtomat** [comment]
I'm assuming this is caused by this issue, but currently the API doesn't think there are any games on at the moment. Possibly because their status is `pending_correction`.

`https://worldcup.sfg.io/matches/current` is returning `[]`;

**Comment by Walkeezy** [comment]
And now it's working perfectly again. Thank you very much for your work @estiens! ✌️

**Comment by estiens** [comment]
Temp workaround in place, will figure out a better one tonight, events and time of match should update in a moment once changes percolate through

**Comment by estiens** [comment]
Issue is that FIFA shows the score of the other match using the same general class as the score of the match being scraped on the live details page. Currently just grabbing the last score shown, but need to search for score only with the parent class of the main match details, not on the page in general.

Note to self

**Comment by CaporalDead** [comment]
If you consume this API with Javascript, here's a small patch we're using on our dashboard : 

```js

                const goals = match[`${team}_events`].reduce((result, item) => {
                    return result + (item.type_of_event.startsWith('goal') ? 1 : 0);
                }, 0);
```

**Comment by estiens** [comment]
@CaporalDead - be aware, I believe one of the event types is goal-own which should count for the other team :)

Fix should be in now, no patch nec

**Comment by CaporalDead** [comment]
Yeah I just saw that @estiens ><'.

**Comment by bklaas** [comment]
API still has the score of Saudi Arabia-Egypt match wrong. There was no own goal in this match, but there was a "goal-penalty", which perhaps is what is driving the incorrect score?

here's the relevant JSON:
{
    "away_team": {
        "code": "EGY",
        "country": "Egypt",
        "goals": 1
    },
    "away_team_country": "Egypt",
    "away_team_events": [
        {
            "country": "Egypt",
            "id": 584,
            "player": "MOHAMED SALAH",
            "team": "EGY",
            "time": "22'",
            "type_of_event": "goal"
        },
        {
            "id": 591,
            "player": "ALI GABR",
            "time": "45'+5'",
            "type_of_event": "yellow-card"
        },
        {
            "id": 593,
            "player": "ABDALLA SAID",
            "time": "45'+7'",
            "type_of_event": "substitution-out"
        },
        {
            "id": 594,
            "player": "AMR WARDA",
            "time": "45'+7'",
            "type_of_event": "substitution-in"
        },
        {
            "id": 599,
            "player": "MARWAN MOHSEN",
            "time": "64'",
            "type_of_event": "substitution-out"
        },
        {
            "id": 600,
            "player": "RAMADAN SOBHY",
            "time": "64'",
            "type_of_event": "substitution-in"
        },
        {
            "id": 610,
            "player": "TREZIGUET",
            "time": "81'",
            "type_of_event": "substitution-out"
        },
        {
            "id": 611,
            "player": "KAHRABA",
            "time": "81'",
            "type_of_event": "substitution-in"
        },
        {
            "id": 613,
            "player": "AHMED FATHI",
            "time": "86'",
            "type_of_event": "yellow-card"
        }
    ],
    "away_team_statistics": {
        "attempts_on_goal": 8,
        "ball_possession": 39,
        "balls_recovered": 49,
        "blocked": 1,
        "clearances": 31,
        "corners": 2,
        "country": "Egypt",
        "distance_covered": 106,
        "fouls_committed": null,
        "num_passes": 361,
        "off_target": 6,
        "offsides": 3,
        "on_target": 1,
        "pass_accuracy": 78,
        "passes_completed": 282,
        "red_cards": 0,
        "tackles": 17,
        "woodwork": 0,
        "yellow_cards": 2
    },
    "datetime": "2018-06-25T14:00:00Z",
    "fifa_id": "300331509",
    "home_team": {
        "code": "KSA",
        "country": "Saudi Arabia",
        "goals": 1
    },
    "home_team_country": "Saudi Arabia",
    "home_team_events": [
        {
            "country": "Saudi Arabia",
            "id": 592,
            "player": "SALMAN ALFARAJ",
            "team": "KSA",
            "time": "45'+6'",
            "type_of_event": "goal-penalty"
        },
        {
            "id": 597,
            "player": "HATAN BAHBRI",
            "time": "65'",
            "type_of_event": "substitution-out"
        },
        {
            "id": 598,
            "player": "MUHANNAD ASIRI",
            "time": "65'",
            "type_of_event": "substitution-in"
        },
        {
            "id": 608,
            "player": "FAHAD ALMUWALLAD",
            "time": "79'",
            "type_of_event": "substitution-out"
        },
        {
            "id": 609,
            "player": "YAHIA ALSHEHRI",
            "time": "79'",
            "type_of_event": "substitution-in"
        },
        {
            "country": "Saudi Arabia",
            "id": 616,
            "player": "SALEM ALDAWSARI",
            "team": "KSA",
            "time": "90'+5'",
            "type_of_event": "goal"
        }
    ],
    "home_team_statistics": {
        "attempts_on_goal": 22,
        "ball_possession": 61,
        "balls_recovered": 46,
        "blocked": 5,
        "clearances": 21,
        "corners": 7,
        "country": "Saudi Arabia",
        "distance_covered": 100,
        "fouls_committed": null,
        "num_passes": 626,
        "off_target": 10,
        "offsides": 1,
        "on_target": 7,
        "pass_accuracy": 88,
        "passes_completed": 548,
        "red_cards": 0,
        "tackles": 7,
        "woodwork": 1,
        "yellow_cards": 0
    },
    "last_event_update_at": "2018-06-25T15:59:04Z",
    "last_score_update_at": "2018-06-25T15:59:04Z",
    "location": "Volgograd Arena",
    "status": "completed",
    "time": "full-time",
    "venue": "Volgograd",
    "winner": "Draw",
    "winner_code": "Draw"
}

**Comment by oooShiny** [comment]
Looks like this is happening for the 2nd group of games. I'm seeing Portugal being given credit for the Morocco goal.

**Comment by inanmahmud92** [comment]
The scores of the matches of Iran vs Portugal and Spain vs Morocco are interchanged.

**Comment by estiens** [comment]
yeah, fixed again, should be going fine now :)

**Comment by estiens** [comment]
Okay, fixed for simultaneous matches, let's keep an eye on it tmrw
