### ISSUE TITLE
Live score showing wrong result in URU vs RUS match

### ISSUE THREAD

**Issue by inanmahmud92** [estiens/world_cup_json#123]
The live scores between URU vs RUS and SAU vs EGY matches are interchanged. Please solve this as early as possible

**Comment by pawelad** [comment]
Yeah, just noticed this as well - I'm guessing that this is the first time that 2 games are played at the same time and the crawler parses the wrong thing.

I'm not really good with Ruby but I'll try and debug this if I have a free moment.

> Please solve this as early as possible
@inanmahmud92 this is a free service, created and maintained by volunteers - please don't use that tone.

**Comment by tronghieu** [comment]
(y)

**Comment by inanmahmud92** [comment]
Sorry for the way I said. :)

**Comment by inanmahmud92** [comment]
@pawelad it would be a great help bro

**Comment by AcriCAA** [comment]
I am noticing an issue with the scores too.

**Comment by pawelad** [comment]
Repo owner commented on #122 - https://github.com/estiens/world_cup_json/issues/122#issuecomment-399977128

I think we should close this one as a duplicate and move the discussion there.

**Comment by estiens** [comment]
Duplicate -- Temp fix in place for parsing scores of duplicate matches (FIFA includes and hides the score of the other live match in the HTML of the match details) - should work for rest of matches, more thorough fix in place later on - see convo in #122
