### ISSUE TITLE
Current match seems to be broken

### ISSUE THREAD

**Issue by CaporalDead** [estiens/world_cup_json#124]
The API is now longer responding with any data (https://worldcup.sfg.io/matches/current) everything thing was fine (except #122) before the half time.

**Comment by Walkeezy** [comment]
Yep, I'm guessing the repo owner is currently working on a fix. Just stay patient. ;-)

**Comment by estiens** [comment]
Should be fixed in approx 1 minute....

**Comment by estiens** [comment]
Fixed now
