### ISSUE TITLE
Scraping only 1 live game

### ISSUE THREAD

**Issue by simofacc** [estiens/world_cup_json#125]
I have an issue where the scraper is only scraping 1 live game Uruguay vs Russia but not the other game. Any idea why?

**Comment by estiens** [comment]
It currently stops checking for live games after it finds one in progress, so if it got one before the other, it wouldn't catch that the other one had started except in a backup task.

try running Scrapers::ScraperTasks.new.check_for_live_game manually and see if the other one gets picked up

**Comment by simofacc** [comment]
I pulled the latest code and added backup_check task to the cron jobs
