### ISSUE TITLE
Incorrect data for fouls and cards in current game.

### ISSUE THREAD

**Issue by oooShiny** [estiens/world_cup_json#126]
This is definitely low priority, but just wanted to bring it to attention.

In `http://worldcup.sfg.io/matches/current` the data being returned for fouls and red/yellow cards seems off. 

First, all fouls are returning `null`.

Also, in the Russia game where they're down to 10 men it doesn't show the red card, or the accumulated yellow cards:

"yellow_cards": 1,
"red_cards": 0,
"fouls_committed": null,

**Comment by estiens** [comment]
hmmm, maybe also something to do with classes changing during simulteanous matches, will add it to list...

**Comment by estiens** [comment]
fouls are corrected now
