### ISSUE TITLE
Group vs Knockout matches

### ISSUE THREAD

**Issue by piercedejong** [estiens/world_cup_json#128]
Just wondering what the best way to differentiate between group and knockout matches is. I am currently using /teams/results but I need to be able to differentiate between a group and knockout win. I thought about using /teams/group_results and subtracting the wins from that page from the wins of /teams/results to get the knockout stage wins. Is this the best way to do it?

**Comment by estiens** [comment]
Could do that now for sure, group or knockout status should be added to match results this week though

**Comment by estiens** [comment]
This is now part of the match information called stage_name

**Comment by piercedejong** [comment]
Awesome, thank you!

**Comment by piercedejong** [comment]
The knockout wins and losses are being counted in group_results wins and losses. Is there any way to stop that from happening.
