### ISSUE TITLE
What's wrong with score?

### ISSUE THREAD

**Issue by naigolf** [estiens/world_cup_json#132]
![image](https://user-images.githubusercontent.com/20389211/41890233-c22c062e-7938-11e8-91f7-e5a270d6f0e6.png)

The score I got
Not true to the competition.

**Comment by estiens** [comment]
hmm? That was very briefly incorrect during the match when it was pulling in from both matches at once but should have been corrected quickly and I checked now and it is reported as 1-1. Not sure when you grabbed this screenshot, but the scraper has been fixed to work with simultaneous matches.

**Comment by estiens** [comment]
yes looks fine and the last score updates were right after the matches
http://worldcup.sfg.io/matches?start_date=yesterday&details=false

**Comment by naigolf** [comment]
Now I use a single day.
https://worldcup.sfg.io/matches/today
I want to update in real time.
You can do that

**Comment by naigolf** [comment]
Thank You....

What do I have to do
When there are two pairs of races simultaneously.

**Comment by estiens** [comment]
nothing special, they will both show up with their stats in real time, just parse them both in your app
