### ISSUE TITLE
Knockout round 90 minutes goals vs 120 mins goals

### ISSUE THREAD

**Issue by roysimha** [estiens/world_cup_json#145]
Hey all,
first of all thanks a lot for the JSON it really is a life saver. For the knockout round I would like to get all the goals up to 90 mins and ignore the ones scored during extension(90 to 120 mins) or penalties. Any idea on how could I achieve that?
Thanks in advance

**Comment by estiens** [comment]
look for a possible update soon that will provide this info. 

You can use team events but note that occasionally goals get duplicated at the moment if they change times. That will also have an update before the knockout rounds I hope!

**Comment by roysimha** [comment]
@estiens That would be great thanks!
