### ISSUE TITLE
Application Error Matches endpoint and slow

### ISSUE THREAD

**Issue by RomainDev25** [estiens/world_cup_json#157]
Hello and thank you very much for your project.
Since this afternoon, I have really slow response of endpoint matches
And I have some time Application Error.
Lot of charge on server ?

Thank you Romain

**Comment by estiens** [comment]
hi, yes, traffic went up by another 20--30 rps and I spun down the dynos to a lower number because not much was going on, I'll get them spun up tonight, and extra during live matches

**Comment by estiens** [comment]
Response times today much better!
