### ISSUE TITLE
Assists in event goal

### ISSUE THREAD

**Issue by pablocesar87** [estiens/world_cup_json#158]
Will you add assists in a further version? For example in the event type `goal` you could add who assisted if someone did. It is the only thing that I am missing to create a good Fantasy football from the scratch.

Off-topic: Will you support eurocup 2020 and worldcup 2022? It would be amazing :D

**Comment by estiens** [comment]
Not sure if we can support euros - probably needs a totally different scraper built, but will def try to support worldcup 2020 if there still isn't a free realtime API :)

If goal assist data in on the FIFA site, it can be added...
