### ISSUE TITLE
Cert is expired

### ISSUE THREAD

**Issue by harrislapiroff** [estiens/world_cup_json#175]
Screenshot from my browser:

<img width="916" alt="Screen Shot 2020-12-31 at 9 27 09 PM" src="https://user-images.githubusercontent.com/296631/103432565-f6af2c00-4bae-11eb-9fe7-e0cc54933ac4.png">

**Comment by estiens** [comment]
Thanks! I don't have control over that domain anymore, my old employer does, but I'll let them know and hopefully they can get it fixed

**Comment by estiens** [comment]
@caseyhelbling - wanna renew cert for worldcup domain? assuming there will be world cups again and there still won't be an API...
