### ISSUE TITLE
Error access - Dangerous query method - https://worldcupjson.net/matches/?by=total_goals

### ISSUE THREAD

**Issue by romain25** [estiens/world_cup_json#190]
Hello, when we access to your Api, we got this error.

message": "Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): \"home_team_score + away_team_score DESC\".This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql()."

Thanks

**Comment by estiens** [comment]
Ah thanks, this is a simple fix and just related to security upgrades in rails. Will have it changed later on today

**Comment by estiens** [comment]
This should be fixed now, thanks!
