### ISSUE TITLE
Datetime value

### ISSUE THREAD

**Issue by cyrusDev1** [estiens/world_cup_json#193]
I got null as value of datetime

**Comment by estiens** [comment]
For the last 16 matches, we won't parse the datetime until we parse times I believe, but I can check the response for those and see if it is already being returned

**Comment by estiens** [comment]
thanks for this report - it was because we had a validation where we couldn't save that without teams yet (which doesn't make sense as they all do have datetimes now) but in looking at that also fixed a few other edge cases for scraping/parsing - should all have values now
