### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by cyrusDev1** [estiens/world_cup_json#197]
Access to XMLHttpRequest at 'https://world-cup-json-2022.fly.dev/matches?start_date=2022-10-16&end_date=2022-10-16' from origin 'https://*****.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I get this error only on mobile browsers

**Comment by estiens** [comment]
Are you proxying from a local URL to that one?

**Comment by cyrusDev1** [comment]
> Are you proxying from a local URL to that one?

No

**Comment by cyrusDev1** [comment]
> Are you proxying from a local URL to that one?

I solved the problem by creating a proxy to which I send the request. Thank you for this awesome api
