### ISSUE TITLE
Not updating...

### ISSUE THREAD

**Issue by guilhermecgs** [estiens/world_cup_json#200]
At least for Qatar x Equador (first game). score is not updating live or updating at all

**Comment by guilhermecgs** [comment]
on all endpoints..  /matches or /matches/today

**Comment by estiens** [comment]
should be fixed now! (always some issues during the first match) but will leave this open in case anyone else is seeing weirdness!

**Comment by xortuna** [comment]
Seems like the /teams api is not updating also

**Comment by lawandothman** [comment]
is the stats scraping not implemented yet? they're not updating for the first match

**Comment by Raghav-Maheshwari** [comment]
the `matches/today` endpoint seems to also be throwing an error:
```
{"message":"undefined method `extra_info' for #\u003cEvent id: 1, type_of_event: \"booking\", player: \"Saad Alsheeb\", time: \"15'\", home_team: true, match_id: 1, created_at: \"2022-11-20 16:56:19.243672000 +0000\", updated_at: \"2022-11-20 16:56:19.243672000 +0000\", fifa_id: \"1_1_15'_booking\", team_id: 1, event_json: \"{\\\"card\\\":1,\\\"period\\\":3,\\\"id_event\\\":null,\\\"event_number...\"\u003e"}
```

**Comment by estiens** [comment]
Leaving this open for tmrws games but all those issues should be fixed

**Comment by rodrigo-m-araujo** [comment]
For England x Iran, scores only updated after the second goal. It still haven't updated after the third goal was scored.
Both on matches and matches/current.

**Comment by zacharylr** [comment]
Looks like it stopped updating at the 50th minute of the game USA-WAL.
