### ISSUE TITLE
Statistics are returning null

### ISSUE THREAD

**Issue by zehfernandes** [estiens/world_cup_json#201]
Hey! 

Thanks for working on the 2022 version 👏
I noticed that the statistics value are all null

![61E92262-98CA-40D7-9770-ECD7B9238C4D](https://user-images.githubusercontent.com/1891339/202938178-bfbd081f-4f7f-43b5-9b57-4a17e979b338.jpeg)

**Comment by estiens** [comment]
Yes, I haven't found them this year in the actual api endpoints. Links welcome!

**Comment by estiens** [comment]
found them , will get them updated for tmrw and beyond this year

**Comment by zehfernandes** [comment]
Uhulll! Amazing @estiens.

Thank you. 🙌

**Comment by estiens** [comment]
Didn't happen yet, but looking now!

**Comment by estiens** [comment]
These should be in there for some past matches and all future matches, we added some and removed some though!

```
"away_team_statistics":{"country":"WAL","attempts_on_goal":6,"attempts_on_goal_against":7,"on_target":1,"off_target":4,"blocked":1,"corners":5,"offsides":1,"num_passes":569,"passes_completed":509,"tackles":4,"free_kicks":11,"goal_kicks":5,"penalties":0,"penalties_scored":0,"throw_ins":22,"yellow_cards":4,"red_cards":0,"fouls_committed":9},"last_checked_at":"2022-11-23T03:27:25Z","last_changed_at":"2022-11-23T03:27:25Z"}
```

**Comment by akozlev** [comment]
Thank you for adding the statistics. 

I am getting the same stats for both home and away teams

>  "home_team_statistics":{"country":"ENG","attempts_on_goal":13,"attempts_on_goal_against":8,"on_target":7,"off_target":3,"blocked":3,"corners":8,"offsides":2,"num_passes":809,"passes_completed":730,"tackles":5,"free_kicks":16,"goal_kicks":5,"penalties":0,"penalties_scored":0,"throw_ins":18,"yellow_cards":0,"red_cards":0,"fouls_committed":12},
"away_team_statistics":{"country":"IRN","attempts_on_goal":13,"attempts_on_goal_against":8,"on_target":7,"off_target":3,"blocked":3,"corners":8,"offsides":2,"num_passes":809,"passes_completed":730,"tackles":5,"free_kicks":16,"goal_kicks":5,"penalties":0,"penalties_scored":0,"throw_ins":18,"yellow_cards":0,"red_cards":0,"fouls_committed":12}

**Comment by estiens** [comment]
That's what I get for adding that late at night- fixed now and rewrote completed games

**Comment by akozlev** [comment]
I am getting null statistics again
