### ISSUE TITLE
show next game on /current feed when no game is on

### ISSUE THREAD

**Issue by mrmay-dev** [estiens/world_cup_json#209]
Just a thought. When there is no "current game" being played maybe the feed could display basic details for the next game.

- ID
- Date and Time
- Venue
- Home and Away Teams 
- Countdown in seconds to next match

Cheers.

**Comment by pedsm** [comment]
I see why you are asking for that (because my front end would also benefit from it) but I think that should be calculated by the front end using the `/today` endpoint.

**Comment by estiens** [comment]
@mrmay-dev: I don't want to break that endpoint because I know in the past people have used any return from that endpoint at all to do something about match in progress

**Comment by mrmay-dev** [comment]
Makes sense.
