### ISSUE TITLE
[url]/teams/ Problem with draw games

### ISSUE THREAD

**Issue by GuiGelinski** [estiens/world_cup_json#211]
Hi,

The end point [url]/teams/ has problem with "draw games"

Statistics like games_played are incorrect,

Thanks for the job!!

**Comment by mrand0** [comment]
Yes.  For draw games, the following are not being updated:

draw:
games_played:
group_points:

**Comment by estiens** [comment]
Fixed - thx!

**Comment by mrand0** [comment]
Thank you Eric for creating/maintain this API.  In the future, I should be able to help with it, if you'd like.
