### ISSUE TITLE
[Request] endpoint "yesterday"

### ISSUE THREAD

**Issue by CyrilNb** [estiens/world_cup_json#214]
Hi, would it be possible to have a "yesterday" like you did with today and tomorrow?

`https://worldcupjson.net/matches/yesterday`

Would love this, way more handy than calculate the yesterday's date and passing it with `start_date` and `end_date`.

Thanks for your awesome job. Truly love your API!

**Comment by estiens** [comment]
sure added!

**Comment by CyrilNb** [comment]
You rock! Thanks so much
