### ISSUE TITLE
Country matches endpoint not working

### ISSUE THREAD

**Issue by YodaLightsabr** [estiens/world_cup_json#217]
The country matches endpoint is returning an error.

Tested with multiple country codes.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/76178582/204068444-be73aec5-6a79-4a2e-8194-472394348f75.png">

```
// 2022-11-25 18:13:15
// https://worldcupjson.net/matches/country?fifa_code=ISL

{
  "message": "undefined method `id' for nil:NilClass\n\n    attributes.each{ |key| _set_value key, _format_keys(object.public_send(key)) }\n                                                              ^^^^^^^^^^^^"
}
```

**Comment by estiens** [comment]
Try this

`https://worldcupjson.net/matches/country/USA?details=true`

**Comment by YodaLightsabr** [comment]
Thanks!
