### ISSUE TITLE
Wrong result for Tunisia - France

### ISSUE THREAD

**Issue by CyrilNb** [estiens/world_cup_json#226]
Hello, 

there is an incorrect result for the match TUNISIA - FRANCE. 

The API says draw 1 -1  but actually the last minute goal for France was offside and did no count.

Thanks

**Comment by hiephm** [comment]
Correctness is the most important aspect of this API, please update result of this match.

**Comment by estiens** [comment]
will manually fixup, this was a result of FIFA calling the game, and then reopening it, the API treats final match status as final. Perhaps I'll add a task to wait until 10 minutes to save winner

**Comment by CyrilNb** [comment]
No worries, I knew it was because of something weird happened at the end of this match. 

It's free API and you are doing incredibly well so far don't listen to impolite people yelling at a free product.

It might be a good idea yeah

Thanks for your work

**Comment by andyewen** [comment]
Thanks for getting this fixed up. I believe France have put in a complaint with FIFA about their disallowed goal. You might have to update the score again depending how that goes! 😆
