### ISSUE TITLE
What is the server's timezone?

### ISSUE THREAD

**Issue by CyrilNb** [estiens/world_cup_json#229]
A user of my project noticed me that the today's matches did not match his real day (he's living in Mexico). 
I am based in Europe so I did not catch the problem before as I saw that the /today endpoint is refreshing at 1am for me (Paris time). But I did not think about other timezone.

How is this handle internally?

**Comment by yasincandev** [comment]
you can use `dayjs` for that 
_https://day.js.org/docs/en/installation/node-js_

you can write like:

```
 dayjs(match.datetime).format("hh:mm A")}
```

**Comment by estiens** [comment]
today uses UTC, but you can pass specific date params as well
