### ISSUE TITLE
/Matches skips match ID 46

### ISSUE THREAD

**Issue by jgarcianewemage** [estiens/world_cup_json#233]
Assigns  ID 47 to match 46

**Comment by 6rak0** [comment]
this is not an issue, ids are fine its just the order of the array that does not match with the ids, you can fix this with .sort()
<img width="412" alt="Captura de Pantalla 2022-12-02 a la(s) 11 58 11" src="https://user-images.githubusercontent.com/12260031/205356089-edc978c1-a375-40ae-ba10-12ea2f7aa012.png">
