### ISSUE TITLE
Women's World Cup 2023?

### ISSUE THREAD

**Issue by jacroe** [estiens/world_cup_json#251]
:wave:  Hi, there!

I was just wondering if you were planning to support WWC 2023? I saw in #184 that it required some (hefty?) changes to get working for 2022. I myself haven't looked yet at what's possible API-wise from FIFA's side, yet, either. But again, just curious if you were going to or not.

Thanks, and best wishes!

**Comment by cole-wilson** [comment]
I would also like to see support for the women's world cup, please let me know what needs to be done.

**Comment by reesericci** [comment]
Came here to ask about women's world cup support so I could keep using @cole-wilson 's site!

**Comment by estiens** [comment]
I did not have time to get it working for this one sorry :( managed to get all then mens and womens world cups, but this one just slipped by, there might be some forks supporting it honestly prob just requires changing team fixtures and BASE URLS for API endpoints
