### ISSUE TITLE
Add SSL?

### ISSUE THREAD

**Issue by icco** [estiens/world_cup_json#53]
It'd be nice if this api was available over HTTPS.

**Comment by estiens** [comment]
Sure, I can add that no problem

**Comment by axelniklasson** [comment]
Would be really sweet, since for example GitHub blocks resources loaded over HTTP when serving main content over HTTPS. Let me know if you need any help!

**Comment by estiens** [comment]
I should get it done this morning I hope. Heroku serves we the right cert when I request it from the command line (for worldcup.sfg.io), but for some reason they serve the herokuapp.com one to the browser right now...

```
$ heroku certs:info
Renewal scheduled for 2018-08-12 01:55 UTC.

Certificate details:
Common Name(s): worldcup.sfg.io
Expires At:     2018-09-12 01:55 UTC
Issuer:         /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
Starts At:      2018-06-14 01:55 UTC
Subject:        /CN=worldcup.sfg.io
SSL certificate is verified by a root authority.
```

**Comment by axelniklasson** [comment]
That's weird. When I visit [worldcup.sfg.io](http://worldcup.sfg.io/), no certificate is loaded at all though.

**Comment by estiens** [comment]
hmmm, still checking

Actually if you need this immediately just use

`https://world-cup-json.herokuapp.com`

**Comment by icco** [comment]
It looks like you need to change your dns to `world-cup-json.herokussl.com.` See https://devcenter.heroku.com/articles/automated-certificate-management#verification-errors for more on this.

```
$ dig worldcup.sfg.io @8.8.8.8

; <<>> DiG 9.10.6 <<>> worldcup.sfg.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17238
;; flags: qr rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;worldcup.sfg.io.		IN	A

;; ANSWER SECTION:
worldcup.sfg.io.	299	IN	CNAME	world-cup-json.herokuapp.com.
world-cup-json.herokuapp.com. 299 IN	CNAME	us-east-1-a.route.herokuapp.com.
us-east-1-a.route.herokuapp.com. 59 IN	A	54.152.236.194
us-east-1-a.route.herokuapp.com. 59 IN	A	52.87.80.61
us-east-1-a.route.herokuapp.com. 59 IN	A	54.156.188.154
us-east-1-a.route.herokuapp.com. 59 IN	A	52.86.40.124
us-east-1-a.route.herokuapp.com. 59 IN	A	54.152.42.186
us-east-1-a.route.herokuapp.com. 59 IN	A	52.73.200.247
us-east-1-a.route.herokuapp.com. 59 IN	A	54.164.102.190
us-east-1-a.route.herokuapp.com. 59 IN	A	54.172.87.254

;; Query time: 84 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Jun 16 19:55:37 UTC 2018
;; MSG SIZE  rcvd: 246
```

**Comment by estiens** [comment]
actually I think we need to change it to heroku's new DNS system which world be would be `worldcup.sfg.io.herokudns.com`

I just can't figure out who has access to the registrar on that one :) We'll get it fixed on Monday, but alternate endpoint should work just fine for HTTPS forever.

**Comment by estiens** [comment]
Thanks for digging though!

**Comment by estiens** [comment]
SSL is added for main domain finally! Cut our redirects by a factor of 10 :)
