### ISSUE TITLE
teams/results not updating

### ISSUE THREAD

**Issue by ChubbyNinja** [estiens/world_cup_json#57]
hey,

Love the API and i'm sure you've got this in hand already, but are you looking to resolve the data not being updated in the teams/results endpoint?

```json
{
"id": 1,
"country": "Russia",
"alternate_name": null,
"fifa_code": "RUS",
"group_id": 1,
"group_letter": "A",
"wins": 0, *
"draws": 0, *
"losses": 0, *
"games_played": 0, *
"points": 0, *
"goals_for": 0, *
"goals_against": 0, *
"goal_differential": 0 *
}

```

**Comment by estiens** [comment]
yup, should all be updating now, sorry had to spend awhile getting the scraper to use JS to update all the events and mark the game as completed, once a game is completed the team results are updated, should occur in real time starting tomorrow :)

**Comment by ChubbyNinja** [comment]
Works perfectly, nicely done
