### ISSUE TITLE
Senegal group matches show "To Be Determined"

### ISSUE THREAD

**Issue by mknabe** [estiens/world_cup_json#60]
Group stage matches for Senegal are showing the country name "To Be Determined" instead of their name. This is possibly happening because Sen is lowercase in the `team.json` file?
```
{
  "group_id": 8,
  "code": "Sen",
  "name": "Senegal"
}
```

**Comment by estiens** [comment]
Thanks for the catch! I'll get it fixed!

**Comment by estiens** [comment]
Fixed now!
