### ISSUE TITLE
Group Results api now working

### ISSUE THREAD

**Issue by t1707** [estiens/world_cup_json#62]
Cheers for your good work guys.
It seems like group_results API is not working, could you have a look over it?

Thanks in advance.

**Comment by t1707** [comment]
Got it
https://github.com/estiens/world_cup_json/blob/master/README.md#try-it-out-well-keep-this-up-through-the-duration-of-the-world-cup
```
http://worldcup.sfg.io/group_results 
```
needs to be changed to 
```
http://worldcup.sfg.io/teams/group_results
```

**Comment by estiens** [comment]
Ah yes, thanks, that first URL was actually deprecated last time around
