### ISSUE TITLE
seems like events stopped updating for the MAR-IRN match after 90+2 minutes

### ISSUE THREAD

**Issue by justcallmelarry** [estiens/world_cup_json#70]

**Comment by PauloAguiar** [comment]
It just changed to "completed" right now, but the score didn't get updated.

**Comment by estiens** [comment]
yeah, there was another hiccup between the main FIFA match reporting site, and the game events page. FIFA keeps returning matches to a future status without a score (probably a bug on their end) after a match is complete, see issue #67 -- thought I had a good workaround in place but not there yet. If I manually open the match up it and set it as in progress, it scrapes the final events and closes the match correctly.

I'll try working around this FIFA bug again.

**Comment by estiens** [comment]
Closing this to refer to #67 - another workaround in place.
