### ISSUE TITLE
Past matches being returned as TBD

### ISSUE THREAD

**Issue by andyewen** [estiens/world_cup_json#81]
Matches that have already taken place are being shown as TBD. Could be a problem with the scraping? 

Here's an example:

```
{  
   "venue":"Moscow",
   "location":"Luzhniki Stadium",
   "status":"future",
   "time":null,
   "fifa_id":"300331552",
   "datetime":"2018-07-15T22:00:00Z",
   "last_event_update_at":null,
   "last_score_update_at":null,
   "home_team":{  
      "country":"To Be Determined",
      "code":"TBD",
      "team_tbd":"W61"
   },
   "away_team":{  
      "country":"To Be Determined",
      "code":"TBD",
      "team_tbd":"W62"
   },
   "winner":null,
   "winner_code":null,
   "home_team_events":"no events available for this match",
   "away_team_events":"no events available for this match"
}
```

**Comment by estiens** [comment]
Hmm, past matches look alright to me, that one is actually the final on July 15th (not June 15th) between the Winner of Game 61 and the Winner of Game 62.

**Comment by andyewen** [comment]
Oh, sorry I think they used to be ordered by their date and that was causing some errors in my app. Thanks for the clarification :)

**Comment by estiens** [comment]
ah yes, I think now you have to pass the ?by_date=DESC param to get it that way (you still can) but it doesn't default to that.
