### ISSUE TITLE
Results for teams (wins, losses... with the possibility of being grouped together

### ISSUE THREAD

**Issue by Angelk90** [estiens/world_cup_json#82]
@estiens : 
Hi, It would be possible to give the possibility to the following api call: http://worldcup.sfg.io/teams/results
that the results are grouped by group as in: http://worldcup.sfg.io/teams/group_results

I would use http://worldcup.sfg.io/teams/group_results, but it does not have the following data:
    "wins": 1,
     "draws": 0,
     "losses": 0,
     "games_played": 1,
     "goals_for": 5,
     "goals_against": 0,
     "goal_differential": 5

Counselor something like this: http://worldcup.sfg.io/teams/results?orderBy=group

**Comment by estiens** [comment]
I can add the data to the group endpoint for you, will do it tomorrow :)

**Comment by estiens** [comment]
Hi there, you can now get all this data via the group results endpoint, you can also pass in a group_id param with either the actual ID or the letter if you want to limit to one group

`http://worldcup.sfg.io/teams/group_results?group_id=B`

**Comment by JacobAbrahamShopify** [comment]
Hi this seems like a cool project I'd like to contribute to. However, Im wondering where in the code you are updating the Database?

**Comment by estiens** [comment]
Scraping code is old and a mess, but it uses `Event.create(attrs)` and `match.save` to save. New scraping code I just made for statistics is much more organized, you can find it under lib/scrapers/fact_scraper

**Comment by Angelk90** [comment]
@estiens :  Thank you, very kind. But for each group, is the list sorted by position? Type first, second, third and fourth for each group? Because I realized that in some groups the placement order seems wrong by making a comparison with the rankings that are on the internet.

**Comment by Angelk90** [comment]
@estiens : Thank you, very kind. But for each group, is the list sorted by position? Type first, second, third and fourth for each group? Because I realized that in some groups the placement order seems wrong by making a comparison with the rankings that are on the internet.

P.S.
I realized that "Arabia Saudi" has changed to "Saudi Arabia" in all the api.

**Comment by estiens** [comment]
It should be sorted by position in group results, but I don't have every single tie-breaker programmed in at the moment. It is sorted by total_points, goal differential, then goals scored, after that it gets into head to head stuff. You can probably program that logic on your own in your app if you want it.

**Comment by Angelk90** [comment]
@estiens : I installed two apps, comparing the ranking of individual groups I realized that they are the same between them but then comparing them with the bees, the bees were ordered differently in the individual groups.
That's why I asked you, because I had different results. ;)

For the thing of the name of Saudi Arabia that I was wondering there was a change?

**Comment by estiens** [comment]
I might add in more head to head ordering later if I have time, but they should be sorted correctly unless two teams are tied in most everything and need to get into the specific head to head matchup criteria.

Not sure about Saudi Arabia, but it should be Saudi Arabia, so seems fine :)

**Comment by Angelk90** [comment]
@estiens: The first image is the ranking taken by an app, the second the data are taken from the API.
![](https://i.imgur.com/ZkeDwla.png)
![](https://i.imgur.com/sb1yo3c.png)

**Comment by estiens** [comment]
I'll try to write some tests for this and add in more tie-breakers sometime this weekend as we get on into the group stage parts where it matters a lot :)

**Comment by camilloaddis** [comment]
Any news regarding this issue? Thanks!
