### ISSUE TITLE
?by_date param produces no result on /match endpoint

### ISSUE THREAD

**Issue by ythecombinator** [estiens/world_cup_json#89]
Hey, first of all, thanks for the amazing project 😄 

My issue here is: I need a way of having the matches organized by stages (e.g. `Group Stage`, `Round of 16`, `Quarter Finals` and so on). I was doing this by just splitting the array I get on `http://worldcup.sfg.io/matches`–and it worked because it was ordered according to the matches' date.

Turns out that suddenly matches from the knockout stage came before matches from the group one on my responses. Then I decided trying `?by_date=ASC` but it doesn't seem to work on `/match` endpoint, I mean, it produces the very same order on the response payload for `?by_date=ASC` and `?by_date=DESC`–it works perfectly on `/matches/today/`, tho.  

Any ideas on what's going on?

**Comment by estiens** [comment]
hmmm, works for me here passing a by_date=desc or by_date=asc....

``` curl http://worldcup.sfg.io/matches/\?by_date\=desc
[{"venue":"Moscow","location":"Luzhniki Stadium","status":"future","time":null,"fifa_id":"300331552","datetime":"2018-07-15T22:00:00Z"```

```
$ curl http://worldcup.sfg.io/matches/\?by_date\=asc
[{"venue":"Moscow","location":"Luzhniki Stadium","status":"completed","time":"full-time","fifa_id":"300331503","datetime":"2018-06-14T15:00:00Z",
```
I did notice it was defaulting to DESC instead of ASC so I put that back.

**Comment by andyewen** [comment]
When it was broken, it was only returning future matches. Could it have been a temporary issue with the scraping?

**Comment by estiens** [comment]
hmmm, probably not, as matches don't change from completed back to future. Let me know if it pops up again. I'll leave this open for now, but assume it is fixed until I hear otherwise

**Comment by estiens** [comment]
This is working fine now

**Comment by ythecombinator** [comment]
Yup, @estiens! Seems to be working out-of-the-box now! Thanks :)
