### ISSUE TITLE
events are gone !

### ISSUE THREAD

**Issue by abysmo46** [estiens/world_cup_json#90]
events are no more in the response (worldcup.sfg.io/matches).

**Comment by estiens** [comment]
Please see the README -- for events in the main response you now have to pass ?details=true

For events and new statistics in the other responses that respond with a smaller number of events, it should default to on (but you can pass details=false if you don't want them

Helped cut down on response time a bit, but if people want them on by default I can switch it back, I didn't think about it being a breaking change for a lot of folks

**Comment by kadinho** [comment]
@estiens for me its good like that, i just need a confirmation matches/today is being updated every minute too ?

**Comment by estiens** [comment]
yes, they all get updated at the same time, just different filters to the db

**Comment by estiens** [comment]
I am turning all events and stats on by default so as not to make a breaking change to the API for people now that we have a cache layer installed.
