### ISSUE TITLE
Last event yellow-card after 90" gets lost

### ISSUE THREAD

**Issue by sachakantor** [estiens/world_cup_json#92]
If a team (any of both teams) receives one or more yellow cards after regular time (90"), the last yellow-card event doesn't appear.

Examples during this world cup 2018, yellow-cards that happened but are not listed by node /matches/?details=true

* Match ID 300353632 (Egypt vs Urugay): Egypt (home team) receives a yellow-card in 90"+4 (source: https://www.fifa.com/worldcup/matches/match/300353632/#match-lineups)

* Match ID 300331529 (Costa Rica vs Serbia): Serbia (away team) receives a yellow-card in 99"+8 (source: https://www.fifa.com/worldcup/matches/match/300331529/#match-lineups)

**Comment by estiens** [comment]
Thanks, I'll check into this. We don't check events after the match is marked as complete by FIFA, there is a chance that events are showing up on the screen AFTER fulltime (sometimes it takes up to 3 minutes for a goal scorer event to show up on that page after the goal is scored for example).

I'll scrape in these past events and then figure out how to handle one last search for late events

**Comment by estiens** [comment]
Might have to wait until later on today when I get all the new scraper code merged as it will be much easier to break out single tasks like this

**Comment by estiens** [comment]
This is fixed in the new scraper code, we go back periodically and add any missed events

**Comment by sachakantor** [comment]
First of all, thank you very much for solving the previous issue.

Now, sadly, I have to report that the same problem applies to goals scored after 90".

*Match ID (Egypt vs Saudi Arabia): Saudi Arabia (away team) scores in 90"+5 (source: https://www.fifa.com/worldcup/matches/match/300331509/#match-lineups)

**Comment by estiens** [comment]
only while a simultaneous event is going on and has ended, fix should percolating through shortly and more permanent workaround in place for tomorrow
