### ISSUE TITLE
Is it possible to fetch a match by its fifa id?

### ISSUE THREAD

**Issue by Rickycezar** [estiens/world_cup_json#95]
It would be nice to be able to fetch match data using something like http://worldcup.sfg.io/matches/300331503

**Comment by estiens** [comment]
yes, I will add that in the next deploy and let you know here

**Comment by Legoburner73** [comment]
@estiens I know this is kinda off topic but since I cannot find anywhere else to ask you this, Do you have a discord? I wanna talk about some things.

**Comment by estiens** [comment]
I don't but you can find me on whatsapp
