### ISSUE TITLE
You broke the scraper again

### ISSUE THREAD

**Issue by Legoburner73** [estiens/world_cup_json#98]
Title. Can you fix this please. I ain't getting data on my end.

I also noticed i was sometimes getting throttled errors. Due to this, I have changed my update time from 10 seconds to 15 seconds. That should maybe help you.

**Comment by Legoburner73** [comment]
@estiens Please take a look at this. Match should be half-time at this point

**Comment by estiens** [comment]
I'm getting data fine here?

You should be able to make up to 2 requests every 5 seconds and not get throttled, but 30s-1min seems like a reasonable request speed. Keep in mind I'm trying to keep this up as a hobby now dealing with 30-40rps, so the less you can ping and still get what you need, the better.

Sometimes the FIFA site lags behind updates, sometimes we lag slightly behind the FIFA site, but the API is usually ahead of even the TV feeds.
